name: Nuestra primera pipeline

on:
    push:
        branches:
            - main
            # - dev
            # - featrue/loquesea

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # - name: fetch last commit
            #   uses: actions/checkout@v4
            #   with:
            #     fetch-depth: 0

            #Descargar el código a nuestra máquina virtual
            - name: checkout repository
              uses: actions/checkout@v4

            #Configurar JDK 17
            - name: configure JDK 17
              uses: actions/setup-java@v1
              with: 
               java-version: '17'

            #Se COMPILA el proyecto
            - name: Build with maven
              run: mvn clean install
               
            #Ejecutamos TEST
            - name: run test
              run: mvn test

            # Save Artifact
            - name: Save artifact
              uses: actions/download-artifact@v4
              with: 
                name: AnimalshelterApplication
                path: target/*.class

    deploy:
        # needs: build
        runs-on: ubuntu-latest

        steps:
         - name: checkout repository
           uses: actions/checkout@v4

         - name: deploy heroku
           uses: actions/checkout@v2
         - uses: CDNievas/heroku-action@v1.0 # This is the action
           with:
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP_NAME}}