name: Nuestra primera pipeline

on:
    push:
        branches:
            - main
            # - dev
            # - featrue/loquesea

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # - name: fetch last commit
            #   uses: actions/checkout@v4
            #   with:
            #     fetch-depth: 0

            #Descargar el código a nuestra máquina virtual
            - name: checkout repository
              uses: actions/checkout@v4

            #Configurar JDK 11
            - name: configure JDK 11
              uses: actions/setup-java@v1
              with: 
                java-version: '11'

            #Se COMPILA el proyecto
            - name: Build with maven
              run: mvn clean install

            #Ejecutamos TEST
            - name: run test
              run: mvn test

            # Save Artifact
            - name: Save artifact
              uses: actions/download-artifact@v4
              with: 
                name: AnimalShellter
                path: target/*.jar